default_platform(:ios)

platform :ios do

app_store_connect_api_key(
  key_id: ENV.fetch("ASC_KEY_ID"),
  issuer_id: ENV.fetch("ASC_ISSUER_ID"),
  key_filepath: ENV.fetch("ASC_KEY_PATH")
)

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"

# =====================================
# 공통 빌드 로직
# =====================================
private_lane :build_with do |options|
scheme = options[:scheme]
app_id = options[:app_identifier]
export_method = options[:export_method] || "app-store"

match(
type: "appstore",
app_identifier: app_id,
readonly: true
)

increment_build_number

build_app(
scheme: scheme,
export_method: export_method,
clean: true,
export_options: {
    provisioningProfiles: {
      app_id => "match AppStore #{app_id}"
    }
  }
)
end

# =====================================
# Debug → TestFlight (Internal)
# =====================================
desc "Debug 스킴 TestFlight 배포"
lane :debug_beta do
build_with(
scheme: "WSSiOS-DEBUG",
app_identifier: ENV.fetch("APP_IDENTIFIER_DEBUG")
)

upload_to_testflight(
app_identifier: ENV.fetch("APP_IDENTIFIER_DEBUG"),
skip_waiting_for_build_processing: true
)
end

# =====================================
# Release → TestFlight
# =====================================
desc "Release 스킴 TestFlight 배포"
lane :release_beta do
build_with(
scheme: "WSSiOS",
app_identifier: ENV.fetch("APP_IDENTIFIER_RELEASE")
)

upload_to_testflight(
skip_waiting_for_build_processing: true
)
end

# =====================================
# Release → App Store 제출
# =====================================
desc "Release 스킴 App Store 제출"
lane :release do
build_with(
scheme: "Release",
app_identifier: ENV.fetch("APP_IDENTIFIER_RELEASE")
)

deliver(
submit_for_review: true,
automatic_release: false
)
end
end
