default_platform(:ios)

platform :ios do
  desc "App Store Connect 배포 (Release)"
  lane :appstore do
    match(type: "appstore")

    build_app(
      scheme: "WSSiOS",
      configuration: "Release",
      export_method: "app-store",
      output_name: "WSSiOS.ipa"
    )

    upload_to_app_store
  end
  
  desc "TestFlight 내부 배포 (Debug)"
  lane :debug do
    match(
      type: "appstore",
      readonly: true,
      app_identifier: "kr.websoso.debug"
    )

    time_based_number = Time.now.strftime("%Y%m%d%H%M")
    increment_build_number(
      build_number: time_based_number,
      xcodeproj: "WSSiOS/WSSiOS.xcodeproj"
    )

    build_app(
      scheme: "WSSiOS",
      configuration: "Debug",
      export_method: "app-store",
      project: "WSSiOS.xcodeproj"
    )

    upload_to_testflight(
      distribute_external: false,
      skip_waiting_for_build_processing: true
    )
  end
end
